### ISSUE TITLE
Issue about mask

### ISSUE THREAD

**Issue by wuhu-wang** [dahyun-kang/cst#4]
Hi, thank for your work. 
Could you share the way you prepare the mask from dataset like coco? My method is using coco api to create mask from annotation and convert it to gray image and convert the bit depth to 8 to adapt to the code. But it seems wrong, the prediction can not compare with it correctly, the accuracy of segmentation can not be calculated.

**Comment by dahyun-kang** [comment]
Hi

For COCO annotation we directly adopt [PFENet's implementation](https://github.com/dvlab-research/PFENet) which uses an annotation pre-processing parsing script from *.json to *.png with integer-valued class label segmentation annotations. You can find it [here](https://github.com/dvlab-research/PFENet/issues/20).

I'm not sure what you meant by "gray image and convert the bit depth to 8 to adapt to the code" though, hope you could figure it out. 

Have a good day! :slightly_smiling_face:

**Comment by wuhu-wang** [comment]
It's useful. Thank you!
Have a nice day!
